import Foundation

enum LanguageDetector {
    static let menuLanguages: [String] = [
        "plaintext",
        "markdown",
        "swift",
        "objectivec",
        "c",
        "cpp",
        "csharp",
        "java",
        "kotlin",
        "scala",
        "javascript",
        "typescript",
        "json",
        "html",
        "xml",
        "css",
        "scss",
        "php",
        "python",
        "ruby",
        "go",
        "rust",
        "elixir",
        "erlang",
        "clojure",
        "lua",
        "perl",
        "r",
        "julia",
        "dart",
        "zig",
        "bash",
        "zsh",
        "powershell",
        "dos",
        "sql",
        "yaml",
        "toml",
        "ini",
        "properties",
        "makefile",
        "dockerfile",
        "cmake",
        "groovy",
        "protobuf",
        "graphql",
        "nginx",
        "apache",
        "latex",
        "asciidoc",
        "diff"
    ]

    private static let filenameMap: [String: String] = [
        ".env": "bash",
        ".bashrc": "bash",
        ".zshrc": "bash",
        ".profile": "bash",
        ".gitignore": "plaintext",
        ".gitattributes": "plaintext",
        ".editorconfig": "ini",
        "makefile": "makefile",
        "gnumakefile": "makefile",
        "dockerfile": "dockerfile",
        "containerfile": "dockerfile",
        "cmakelists.txt": "cmake",
        "jenkinsfile": "groovy",
        "vagrantfile": "ruby",
        "gemfile": "ruby",
        "rakefile": "ruby",
        "podfile": "ruby",
        "brewfile": "ruby",
        "fastfile": "ruby",
        "appfile": "ruby",
        "matchfile": "ruby",
        "deliverfile": "ruby",
        "scanfile": "ruby",
        "snapfile": "ruby",
        "gymfile": "ruby",
        "justfile": "makefile",
        "procfile": "yaml",
        "package-lock.json": "json",
        "composer.lock": "json",
        "cargo.lock": "toml"
    ]

    private static let extensionMap: [String: String] = [
        "adoc": "asciidoc",
        "asciidoc": "asciidoc",
        "apacheconf": "apache",
        "asm": "x86asm",
        "astro": "xml",
        "bat": "dos",
        "bib": "bibtex",
        "swift": "swift",
        "m": "objectivec",
        "mm": "objectivec",
        "h": "objectivec",
        "c": "c",
        "cc": "cpp",
        "cpp": "cpp",
        "cxx": "cpp",
        "hpp": "cpp",
        "cs": "csharp",
        "java": "java",
        "kt": "kotlin",
        "kts": "kotlin",
        "scala": "scala",
        "sc": "scala",
        "js": "javascript",
        "jsx": "javascript",
        "mjs": "javascript",
        "cjs": "javascript",
        "ts": "typescript",
        "tsx": "typescript",
        "json": "json",
        "jsonc": "json",
        "ipynb": "json",
        "html": "html",
        "htm": "html",
        "ejs": "xml",
        "vue": "xml",
        "svelte": "xml",
        "xml": "xml",
        "plist": "xml",
        "xib": "xml",
        "storyboard": "xml",
        "css": "css",
        "scss": "scss",
        "sass": "scss",
        "md": "markdown",
        "mdx": "markdown",
        "markdown": "markdown",
        "mkd": "markdown",
        "rst": "markdown",
        "php": "php",
        "phtml": "php",
        "py": "python",
        "pyw": "python",
        "rb": "ruby",
        "go": "go",
        "rs": "rust",
        "ex": "elixir",
        "exs": "elixir",
        "erl": "erlang",
        "hrl": "erlang",
        "clj": "clojure",
        "cljs": "clojure",
        "lua": "lua",
        "pl": "perl",
        "pm": "perl",
        "r": "r",
        "jl": "julia",
        "dart": "dart",
        "zig": "zig",
        "sh": "bash",
        "bash": "bash",
        "zsh": "bash",
        "fish": "bash",
        "ps1": "powershell",
        "psm1": "powershell",
        "cmd": "dos",
        "sql": "sql",
        "yml": "yaml",
        "yaml": "yaml",
        "toml": "toml",
        "ini": "ini",
        "cfg": "ini",
        "conf": "ini",
        "xcconfig": "ini",
        "properties": "properties",
        "props": "properties",
        "mk": "makefile",
        "mak": "makefile",
        "make": "makefile",
        "dockerfile": "dockerfile",
        "cmake": "cmake",
        "gradle": "groovy",
        "groovy": "groovy",
        "proto": "protobuf",
        "graphql": "graphql",
        "gql": "graphql",
        "nginx": "nginx",
        "tex": "latex",
        "latex": "latex",
        "diff": "diff",
        "patch": "diff"
    ]

    static func detectLanguage(for url: URL?, contents: String) -> String? {
        if let shebang = contents.split(separator: "\n", maxSplits: 1, omittingEmptySubsequences: false).first,
           shebang.hasPrefix("#!") {
            let line = String(shebang).lowercased()
            if line.contains("python") { return "python" }
            if line.contains("node") { return "javascript" }
            if line.contains("ruby") { return "ruby" }
            if line.contains("php") { return "php" }
            if line.contains("perl") { return "perl" }
            if line.contains("zsh") { return "bash" }
            if line.contains("bash") || line.contains("sh") { return "bash" }
        }

        if let filename = url?.lastPathComponent.lowercased(),
           let language = filenameMap[filename] {
            return language
        }

        guard let ext = url?.pathExtension.lowercased(), !ext.isEmpty else {
            return contents.trimmingCharacters(in: .whitespacesAndNewlines).hasPrefix("{") ? "json" : "plaintext"
        }
        return extensionMap[ext] ?? "plaintext"
    }
}
